# python3 supervised_finetuning.py \
# --model_name_or_path /home/jack/Projects/yixin-llm/yixin-llm-data/MedicalGPT/weights/Qwen2.5-VL-7B-Instruct \
CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 2 supervised_finetuning.py \
    --model_name_or_path Qwen/Qwen2.5-0.5B-Instruct \
    --train_file_dir ./new_tool_instruct/train \
    --validation_file_dir ./new_tool_instruct/val \
    --cache_dir ./model_v0 \
    --device_map "cuda" \
    --use_peft True \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout 0.05 \
    --per_device_train_batch_size 16 \
    --do_train \
    --num_train_epochs 10 \
    --per_device_eval_batch_size 16 \
    --max_train_samples -1 \
    --learning_rate 3e-5 \
    --warmup_ratio 0.2 \
    --model_max_length 2048 \
    --weight_decay 0.01 \
    --logging_dir ./runs \
    --logging_strategy steps \
    --logging_steps 1 \
    --save_steps 400 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 10 \
    --output_dir outputs-full-sft-v0 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --torch_dtype bfloat16 \
    --report_to tensorboard \
    --neft_alpha 8 \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --template_name chatglm3 \
    --deepspeed ./zero2.json \
    --bf16
